### ISSUE TITLE
FirstRDD  - fails on Windows

### ISSUE THREAD

**Issue by belgoros** [arey/initiation-spark-java#1]
It fails when running on a Windows 8 PC beacuse of extra slash `/D:`:

```
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 2: /D:/projects/sparky-cdn/target/classes/ratings.txt
    at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
    at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
    at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
    at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
    at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
    at java.nio.file.Paths.get(Paths.java:84)
    at com.sncf.app.FirstRDD .main(FirstRDD .java:21)
```

I had to modify the `main` method to make it pass as folllows:

```
public static void main(String... args) {
    FirstRDD runner = new FirstRDD ();
    SparkConf conf = new SparkConf().setAppName("Sparky CDN").setMaster("local[*]");
    JavaSparkContext sc = new JavaSparkContext(conf);

    Path path = runner.getFilePath(runner.getFile());
    JavaRDD<String> lines = sc.textFile(path.toString());
    System.out.println("Lines count: " + lines.count());
    }

    private File getFile() {
    ClassLoader classLoader = getClass().getClassLoader();
    File file = new File(classLoader.getResource("ratings.txt").getFile());

    return file;
    }

    private Path getFilePath(File file) {
    Path path = Paths.get(file.toURI());

    return path;
    }
```

**Comment by arey** [comment]
Thanks @Javix
